Check enviroment for needed programs

diff --git a/h2i b/h2i
--- a/h2i
+++ b/h2i
@@ -2,32 +2,32 @@
 
 # title           : h2i - homematic two influx
 # description     : Pull data from homematic ccu via xmlapi and stores them inside a time series database like influxdb.
-# author		      : Torsten Scholz (https://github.com/TorstenScholz/h2i)
+# author          : Torsten Scholz (https://github.com/TorstenScholz/h2i)
 # License         : GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
 # date            : 02.02.2023
-# version         : 1.1.0    
-# usage		        : h2i [command] [option]
-# notes           : Linux tools: curl, awk, cut, sed and xmllint must be installed.
+# version         : 1.2.0
+# usage           : h2i [command] [option]
+# notes           : Linux tools: xmllint, curl, awk, cut and sed must be installed.
 
 
 # Define Variables
 PROGRAM="h2i"
-VERSION="1.1.0"
+VERSION="1.2.0"
 error=""
 ccudata="homematic.data"                                      # Path and filename for ccu.data file
 statelist="statelist.xml"                                     # Path and filename for statelist.xml file
-ccu="http://192.168.0.20/addons/xmlapi/statelist.cgi"         # URL where statelist.xml can be pulled from
-#db_user="admin"                                              # User of influxdb
-#db_pass="*********"                                          # Passord of influxdb
-#db_url="http://localhost:8086/write?db=grafana"              # URL of influxdb with port and database 
+ccu="http://192.168.2.20/addons/xmlapi/statelist.cgi"         # URL where statelist.xml can be pulled from
+db_user="admin"                                               # User of influxdb
+db_pass="*********"                                           # Passord of influxdb
+db_url="http://localhost:8086/write?db=h2i"                   # URL of influxdb with port and database 
 
 
 # Set Enviroment
-xmllint="/usr/bin/$xmllint"
-curl="/usr/bin/curl"
-awk="/usr/bin/awk"
-cut="/usr/bin/cut"
-sed="/bin/sed"
+xmllint=`command -v xmllint` || { echo "I require 'xmllint' but it's not installed. Use your package manager to install it or visit 'http://www.xmlsoft.org'. Aborting."; exit 1; }
+curl=`command -v curl` || { echo "I require 'curl' but it's not installed. Use your package manager to install it or visit 'https://curl.se'. Aborting."; exit 1; }
+awk=`command -v awk` || { echo "I require 'awk' but it's not installed. Use your package manager to install it. Aborting."; exit 1; }
+cut=`command -v cut` || { echo "I require 'cut' but it's not installed. Use your package manager to install it. Aborting."; exit 1; }
+sed=`command -v sed` || { echo "I require 'sed' but it's not installed. Use your package manager to install it. Aborting."; exit 1; }
 echo -n "" > $ccudata
 
 
@@ -37,10 +37,10 @@ echo -n "" > $ccudata
 # HINT: No empty line at the beginnig or end. First the ID then the values separated by commas.
 
 list_of_ids="6123,SET_TEMPERATURE,ACTUAL_TEMPERATURE,ACTUAL_HUMIDITY,BATTERY_STATE,LOWBAT
+2469,SET_TEMPERATURE,ACTUAL_TEMPERATURE,VALVE_STATE,BATTERY_STATE,LOWBAT
 3564,ENERGY_COUNTER,POWER,CURRENT,VOLTAGE,FREQUENCY,STATE
 7846,ACTUAL_TEMPERATURE,HUMIDITY,ILLUMINATION,RAIN_COUNTER,SUNSHINEDURATION,WIND_DIR,WIND_DIR_RANGE,WIND_SPEED,LOW_BAT
-2422,STATE,LOWBAT"
-
+6185,STATE,LOWBAT"
 
 # Function: Get statelist.xml
 get_statelist () {
@@ -59,12 +59,12 @@ parse_xml () {
     # Device not found in xml
     echo "ERROR: Device name: "$device_id" not found in xml"
     exit 1
-    
+
   elif ! $xmllint --xpath $xpath "$statelist" > /dev/null; then
     # Type not found in xml
     echo "ERROR: Device type: "$device_type" not found in xml"
     exit 1
-    
+
   else
     # Parse data into variables 
     name=`$xmllint --xpath //device[@ise_id="$device_id"] "$statelist" | $awk -F= '$1=="name"{print $2}' RS=' ' | $sed -n "1p"  | $sed 's/^"//;s/"$//'`
@@ -146,7 +146,7 @@ case $COMMAND in
       echo "DEBUG INFO:"
       cat $ccudata
     fi
-    
+
     echo "No error"
   ;;
 
@@ -206,4 +206,3 @@ unset end
 
 # Exit
 exit 0
-
